/* -------------------------------------------------------------------------- */
/*  AUTO-GENERATED TYPES FROM ENHANCED REGISTRY                              */
/*  – This file demonstrates how TypeScript types can be auto-generated      */
/*  – In production, this would be generated during build process           */
/*  – For now it shows the potential of the enhanced registry system        */
/* -------------------------------------------------------------------------- */

// This file demonstrates auto-generated TypeScript interfaces
// In a full implementation, this would be generated automatically during build

import type { Node, Position } from '@xyflow/react';
import { generateTypeDefinitions } from '../../nodes/nodeRegistry';

// ============================================================================
// AUTO-GENERATED INTERFACES (Example)
// ============================================================================

export interface ViewOutputData {
  label: string;
  isActive: boolean;
  displayedValues: Array<{ type: string; content: any; id: string; }>;
}

export interface ViewOutputRefactorData {
  displayedValues: Array<{ type: string; content: any; id: string; }>;
  isActive: boolean;
}

export interface CreateTextEnhancedData {
  text: string;
  output: string;
  isEnabled: boolean;
  prefix: string;
  maxLength: number;
  isActive: boolean;
}

export interface TriggerOnToggleRefactorData {
  triggered: boolean;
  value: boolean;
  outputValue: boolean;
  type: string;
  label: string;
  inputCount: number;
  hasExternalInputs: boolean;
  isActive: boolean;
}

// ============================================================================
// AUTO-GENERATED UNION TYPE (Example)
// ============================================================================

export type AutoGeneratedAgenNode =
  | (Node<ViewOutputData & Record<string, unknown>> & { type: 'viewOutput'; targetPosition: Position })
  | (Node<ViewOutputRefactorData & Record<string, unknown>> & { type: 'viewOutputRefactor'; targetPosition: Position })
  | (Node<CreateTextEnhancedData & Record<string, unknown>> & { type: 'createTextEnhanced' })
  | (Node<TriggerOnToggleRefactorData & Record<string, unknown>> & { type: 'triggerOnToggleRefactor' });

// ============================================================================
// UTILITY TO GET RAW GENERATED CODE
// ============================================================================

export const getGeneratedTypeDefinitions = () => {
  return generateTypeDefinitions();
};

// Example usage:
// console.log(getGeneratedTypeDefinitions()); 